Sistema de Cadastro de Contato/SistemaCadastro/Models/ContatoModel.cs
namespace SistemaCadastro.Models
{
    public class ContatoModel
    {
        public int Id {get; set;}

        public string? Nome {get; set;}

        public string? Email {get; set;}

        public string? Numero {get; set;}
    }
}

Sistema de Cadastro de Contato/SistemaCadastro/Models/ErrorViewModel.cs
namespace SistemaCadastro.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Sistema de Cadastro de Contato/SistemaCadastro/Models/HomeModel.cs
namespace SistemaCadastro.Models;

public class HomeModel
{
}

Sistema de Cadastro de Contato/SistemaCadastro/Controllers/ContatoController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SistemaCadastro.Models;
using SistemaCadastro.Repositorio;

namespace SistemaCadastro.Controllers;

public class ContatoController : Controller
{

    private readonly IContatoRepositorio _contatoRepositorio;//fazendo a injeção de dependencia

    public ContatoController(IContatoRepositorio contatoRepositorio){

        _contatoRepositorio = contatoRepositorio;
    }

    public IActionResult Index()
    {
        
        List <ContatoModel> contatos = _contatoRepositorio.BuscarContatos();

        return View(contatos);
    }

    public IActionResult Criar()
    {
        

        return View(); //redireciona para index

    }
    [HttpPost]
    public IActionResult Criar(ContatoModel contato)
    {
        _contatoRepositorio.Adicionar(contato);

        return RedirectToAction("Index"); //redireciona para index

    }

    public IActionResult Editar(int id)
    {
      ContatoModel contato = _contatoRepositorio.ListarId(id);

        return View(contato);
    }

[HttpPost]
    public IActionResult Atualizar(ContatoModel contato)
    {
        _contatoRepositorio.Atualizar(contato);

        return RedirectToAction("Index"); //redireciona para index

    }

    public IActionResult ConfirmarRemover(int id)
    {
      ContatoModel contato = _contatoRepositorio.ListarId(id);   
        return View(contato);
    }

     public IActionResult Remover(int id)
    {
         _contatoRepositorio.Remover(id);

        return RedirectToAction("Index"); //redireciona para index

    }
}

Sistema de Cadastro de Contato/SistemaCadastro/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SistemaCadastro.Models;

namespace SistemaCadastro.Controllers;

public class HomeController : Controller
{

    public IActionResult Index()
    {
        
            return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Sistema de Cadastro de Contato/SistemaCadastro/Views/Contato/ConfirmarRemover.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Confirmação Remover Contatos";
}


<div class="text-center">

    <h3>Realmente deseja apagar o contato (@Model.Nome)?</h3>

</div>

<a class="btn btn-primary" role="button" asp-controller="Contato" asp-action="Index">Cancelar Exclusão</a>
<a class="btn btn-danger" role="button" asp-route-id = "@Model.Id" asp-controller="Contato" asp-action="Remover">Confirmar Exclusão</a>

Sistema de Cadastro de Contato/SistemaCadastro/Views/Contato/Criar.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Criar Contatos";
}


<div class="text-center">

    <h1 class="display-4"><strong>Adicionar Contato</strong></h1>

</div>

<form asp-asp-controller="Contato" asp-action="Criar" method="post">
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for = "Nome" class="form-control" placeholder="Digite o nome do contato">

    </div>

    <div class="form-group">
        <label for="email">E-mail</label>
        <input type="text" asp-for = "Email" class="form-control" placeholder="Digite o e-mail do contato">

    </div>

    <div class="form-group">
        <label for="email">Numero do Contato</label>
        <input type="text" asp-for = "Numero" class="form-control" placeholder="Digite o numero de contato">

    </div>
    <br>
    <button type="submit" class="btn btn-primary ">Adicionar</button>
    <a class="btn btn-secondary " asp-controller="Contato" asp-action="Index" role="button">Voltar</a>
</form>

Sistema de Cadastro de Contato/SistemaCadastro/Views/Contato/Editar.cshtml
@model ContatoModel;
@{
    ViewData["Title"] = "Editar Contatos";
}


<div class="text-center">

    <h1 class="display-4"><strong>Editar Contato</strong></h1>

</div>



<form asp-asp-controller="Contato" asp-action="Atualizar" method="post">

    <input type="hidden" asp-for="Id">

    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for = "Nome" class="form-control" placeholder="Digite o nome do contato">

    </div>

    <div class="form-group">
        <label for="email">E-mail</label>
        <input type="text" asp-for = "Email" class="form-control" placeholder="Digite o e-mail do contato">

    </div>

    <div class="form-group">
        <label for="email">Numero do Contato</label>
        <input type="text" asp-for = "Numero" class="form-control" placeholder="Digite o numero de contato">

    </div>
    <br>
    <button type="submit" class="btn btn-primary ">Alterar</button>
    <a class="btn btn-secondary " asp-controller="Contato" asp-action="Index" role="button">Voltar</a>
</form>

Sistema de Cadastro de Contato/SistemaCadastro/Views/Contato/Index.cshtml
@model List<ContatoModel>
@{
  ViewData["Title"] = "Lista de Contatos";
}

<div class = "text-center">

<div class = "d-grid gap-2 d-md-flex justify-content-md-start"> 
  <a class="btn btn-primary" role = "button" asp-controller="Contato" asp-action="Criar">Adicionar novo contato</a>
  </div>
<br>
<h1 class="display-4"><strong>Listagem de Contatos</strong></h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Nome</th>
      <th scope="col">E-mail</th>
      <th scope="col">Contato</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    @if(Model != null && Model.Any())
    {
      foreach (ContatoModel contato in Model)
      {
        <tr>
          <th scope = "row">@contato.Id</th>
          <td>@contato.Nome</td>
          <td>@contato.Email</td>
          <td>@contato.Numero</td>
          <td>
              <div class="btn-group" role="group">
                <a role="button" class="btn btn-primary" asp-route-id = "@contato.Id" asp-controller="Contato" asp-action="Editar">Editar</a>
                <a role="button" class="btn btn-danger"  asp-route-id = "@contato.Id" asp-controller="Contato" asp-action="ConfirmarRemover">Apagar</a>
                </div>
          </td>
          </tr>

      }
    }
  </tbody>
</table>
</div>

Sistema de Cadastro de Contato/SistemaCadastro/Views/Home/Index.cshtml
@model HomeModel
@{
    ViewData["Title"] = "Pagina Inicial";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo!</h1>
   
    <p>Sistema de Controle de Contatos</p>
</div>

Sistema de Cadastro de Contato/SistemaCadastro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Controle de Contatos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaCadastro.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Controle de Contatos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Pagina Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contato" asp-action="Index">Contatos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Controle de Contatos 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>